/**
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

let prevTerm = 1;
let nextTerm = 2;
let result = 0;
let counter = nextTerm;

while ( counter < 4000000) {

  if(counter % 2 === 0) result += counter;

  counter = prevTerm + nextTerm;
  prevTerm = nextTerm;
  nextTerm = counter;

};

console.log('result: ', result);
