/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
 */

  function fibonacci(number) {
    let terms = [1, 2]
    let sum = terms[1];

    for(let i = 2; i < number; i++){
      terms[i] = terms[i-2] + terms[i-1];
      
      if(terms[i] % 2 === 0 && terms[i] < number) sum += terms[i]; 
    }

    console.log(sum);
  }

  fibonacci(5);
  fibonacci(10);
  fibonacci(15);
  fibonacci(20);
  fibonacci(30);
